from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DESCRIPTIONS = {
    'integrar.py': 'Regenera os grafos core/topo e QSF/QPF a partir dos contratos e CSV congelados. Os layouts permanecem separados em config/layouts e nÃƒÂ£o sÃƒÂ£o sobrescritos. Usa somente BDF para sÃƒÂ­ntese. ApÃƒÂ³s executar, validar_refatoracao.py deve conferir hashes das invariantes e a reproduÃƒÂ§ÃƒÂ£o dos BDF/BSF; preparar.py aplica a ordem filhos antes de pais.',
    'validar_estrutura.py': 'Confere os 16 grafos: nomes, portas, larguras, drivers e ciclos. Usa os sÃƒÂ­mbolos de primitivas preservados em config/primitivas, permitindo validaÃƒÂ§ÃƒÂ£o sem Quartus instalado. NÃƒÂ£o prova continuidade geomÃƒÂ©trica: essa prova fica em validar_geometria.py, que lÃƒÂª os BDF finais por contato fÃƒÂ­sico. BUF conserva a expansÃƒÂ£o em dois NOT. Resultados atuais e pendÃƒÂªncias em docs/REFATORACAO_VISUAL_TECNICA.md.',
    'preparar.py': 'Gera BDF/BSF canÃƒÂ´nicos em ordem hierÃƒÂ¡rquica e audita geometricamente antes de exportar. --generate-only funciona sem Quartus e registra native=PENDING; --export-only analisa/exporta os BDF jÃƒÂ¡ existentes sem refazer layout. SÃƒÂ­mbolos nativos de conferÃƒÂªncia ficam em simulation/generated/native_symbols e nunca substituem a geometria canÃƒÂ´nica entregue. Portas BSF/HDL sÃƒÂ£o conferidas contra o contrato. Logs e hashes de proveniÃƒÂªncia atual em docs/preparacao_atual.json; HDL/logs anteriores sÃƒÂ£o histÃƒÂ³ricos atÃƒÂ© nova exportaÃƒÂ§ÃƒÂ£o. --root, --quartus e --modules selecionam contexto. NÃƒÂ£o aprova legibilidade.',
    'gerar_pinagem.py': 'Extrai os pinos das pÃƒÆ’Ã‚Â¡ginas 36..39 do manual DE2-115 usando pypdf, cobrindo os 96 sinais declarados. Rejeita ausÃƒÆ’Ã‚Âªncia ou duplicaÃƒÆ’Ã‚Â§ÃƒÆ’Ã‚Â£o de sinal/pino. JP6 e pinos fixos 3,3 V usam 3.3-V LVTTL; JP7 e pinos fixos 2,5 V usam 2.5 V. Exemplo: python scripts/gerar_pinagem.py caminho/DE2_115_User_manual.pdf. O CSV foi conferido com as imagens do enunciado e com as atribuiÃƒÆ’Ã‚Â§ÃƒÆ’Ã‚Âµes reais do Fitter. O manual externo ÃƒÆ’Ã‚Â© necessÃƒÆ’Ã‚Â¡rio sÃƒÆ’Ã‚Â³ para regenerar o CSV, nÃƒÆ’Ã‚Â£o para compilar o projeto.',
    'compilar.ps1': 'Executa quartus_sh --flow compile ULA_DE2_115 na raiz do projeto e falha se o processo retornar erro. Aceita -Quartus para o bin64 instalado. A compilaÃƒÆ’Ã‚Â§ÃƒÆ’Ã‚Â£o real inclui anÃƒÆ’Ã‚Â¡lise/sÃƒÆ’Ã‚Â­ntese, fitting, assembly, TimeQuest e EDA writer. NÃƒÆ’Ã‚Â£o programa a placa. Exemplo: scripts/compilar.ps1. A revisÃƒÆ’Ã‚Â£o final passou com zero erros; os avisos sÃƒÆ’Ã‚Â£o indexados e explicados em docs/VALIDACAO.md.',
    'render_evidencias.py': 'LÃƒÆ’Ã‚Âª diretamente a ÃƒÆ’Ã‚Â¡rvore BDF e renderiza sÃƒÆ’Ã‚Â­mbolos, coordenadas, primitivas e conectores em PNG. LÃƒÆ’Ã‚Âª o VCD realmente executado para criar recortes de sinais observados; nÃƒÆ’Ã‚Â£o calcula respostas esperadas. --circuits-only dispensa VCD. Usa Pillow e Arial local. Exemplo: python scripts/render_evidencias.py. As figuras sÃƒÆ’Ã‚Â£o documentaÃƒÆ’Ã‚Â§ÃƒÆ’Ã‚Â£o programÃƒÆ’Ã‚Â¡tica do circuito e evidÃƒÆ’Ã‚Âªncia de simulaÃƒÆ’Ã‚Â§ÃƒÆ’Ã‚Â£o, sem screenshot ou conferÃƒÆ’Ã‚Âªncia da interface Quartus. O VCD completo preserva casos que nÃƒÆ’Ã‚Â£o cabem no recorte.',
    'verificar_entrega.py': 'Exige proveniÃƒÂªncia nativa atual e hashes coincidentes de fontes/HDL/logs antes de aceitar testes, compilaÃƒÂ§ÃƒÂ£o ou recursos/pinagem do Fitter. Rejeita resultados anteriores ÃƒÂ  refatoraÃƒÂ§ÃƒÂ£o. Confere 16 BDF exclusivos no QSF, contratos, zero estado e 96 pinos/I/O. --manifest atualiza hashes somente apÃƒÂ³s todas as etapas nativas passarem. NÃƒÂ£o aprova revisÃƒÂ£o visual ou placa.',
    'limpar_gerados.py': 'Remove apenas comentÃƒÆ’Ã‚Â¡rios nÃƒÆ’Ã‚Â£o legais de arquivos gerados, mantendo strings e avisos de Copyright/License Agreement. Antes de gravar exige igualdade dos tokens funcionais entre original e versÃƒÆ’Ã‚Â£o limpa. Exemplo: python scripts/limpar_gerados.py simulation/netlist/ula_de2_115.vo. A netlist foi compilada/simulada novamente depois da limpeza e o ZIP serÃƒÆ’Ã‚Â¡ recompilado com os sÃƒÆ’Ã‚Â­mbolos limpos. CabeÃƒÆ’Ã‚Â§alhos legais preservados sÃƒÆ’Ã‚Â£o a exceÃƒÆ’Ã‚Â§ÃƒÆ’Ã‚Â£o documentada ÃƒÆ’Ã‚Â  ausÃƒÆ’Ã‚Âªncia literal de comentÃƒÆ’Ã‚Â¡rios.',
    'simular_netlist.ps1': 'Exige compilação atual e fontes coincidentes registradas por validar_nativo.py; não usa a netlist histórica para aprovar BDF novos. Resultados atuais em docs/REFATORACAO_VISUAL_TECNICA.md. Descrição histórica do fluxo: gera .vo funcional pelo EDA Netlist Writer apÃƒÆ’Ã‚Â³s a compilaÃƒÆ’Ã‚Â§ÃƒÆ’Ã‚Â£o dos BDF e simula no Icarus com cycloneive_atoms.v da instalaÃƒÆ’Ã‚Â§ÃƒÆ’Ã‚Â£o Quartus. Usa o testbench independente do topo em pasta isolada para preservar seu VCD modular. Aceita -IcarusRoot e -Quartus. Exemplo: scripts/simular_netlist.ps1. Passou nas 16384 verificaÃƒÆ’Ã‚Â§ÃƒÆ’Ã‚Âµes (8192 entradas ÃƒÆ’Ã‚Âºnicas), apÃƒÆ’Ã‚Â³s limpeza da netlist. O comando legado quartus_map --generate_functional_sim_netlist nÃƒÆ’Ã‚Â£o ÃƒÆ’Ã‚Â© usado porque falhou com erro 281041 para Cyclone IV E. NÃƒÆ’Ã‚Â£o aplica SDF e nÃƒÆ’Ã‚Â£o valida orÃƒÆ’Ã‚Â§amento fÃƒÆ’Ã‚Â­sico.',
    'empacotar.py': 'Cria ZIP com entrega/ como raiz, excluindo caches db/incremental_db, __pycache__, work e saÃƒÆ’Ã‚Â­das automÃƒÆ’Ã‚Â¡ticas modelsim nÃƒÆ’Ã‚Â£o selecionadas. Inclui fontes, documentos, evidÃƒÆ’Ã‚Âªncias e relatÃƒÆ’Ã‚Â³rios nativos relevantes. --extract exige diretÃƒÆ’Ã‚Â³rio novo e rejeita travessia de caminho antes de extrair. Exemplo: python scripts/empacotar.py --extract tmp/recompilacao_zip. O teste de portabilidade requer compilar a cÃƒÆ’Ã‚Â³pia extraÃƒÆ’Ã‚Â­da e conferir pinos/estado, sem depender do banco original.',
    'documentar_apoio.py': 'Escreve documentos de apoio dos scripts e grafos core/topo. MantÃƒÂ©m descriÃƒÂ§ÃƒÂ£o do fluxo canÃƒÂ´nico e separa checks offline, histÃƒÂ³rico nativo e pendÃƒÂªncias atuais. NÃƒÂ£o altera implementaÃƒÂ§ÃƒÂ£o nem transforma logs histÃƒÂ³ricos em aprovaÃƒÂ§ÃƒÂ£o da revisÃƒÂ£o refatorada.'
}


def main():
    for name, description in DESCRIPTIONS.items():
        (ROOT / 'scripts' / (name + '.md')).write_text('# ' + name + '\n\n' + description + '\n', encoding='utf-8', newline='\n')
    for name in ('ula_core', 'ula_de2_115'):
        (ROOT / 'config/grafos' / (name + '.json.md')).write_text(f'# {name}.json\n\nGrafo autoral de portas e redes da integracao aprovada. Instancias possuem entidade/primitiva, nome e conexoes por porta com intervalos explicitos de barramento. Emitido por integrar.py e lido por gerar_bdf.py; implementacao real em modulos/{name}.bdf, documentada em {name}.bdf.md. As interfaces sao do contrato congelado; config/layouts conserva o posicionamento separado. Verificacoes atuais e pendencias em docs/REFATORACAO_VISUAL_TECNICA.md. Registros nativos anteriores nao aprovam os BDF refatorados.\n', encoding='utf-8', newline='\n')
    (ROOT / 'docs/verificacao_final.json.md').write_text('# verificacao_final.json\n\nEstado atual PENDING_NATIVE enquanto faltam exportacao, testes e compilacao da revisao refatorada. O PASS anterior esta em historico_pre_refatoracao/verificacao_final.json. verificar_entrega.py exige proveniencia nativa atual antes de escrever PASS com pinos/Fitter/recursos/SOF. Nao confirma jumpers, conferencia visual ou placa.\n', encoding='utf-8', newline='\n')
    (ROOT / 'manifest.json.md').write_text('# manifest.json\n\nEnquanto a validacao nativa atual estiver PENDING, o manifesto existente e historico anterior a refatoracao e nao corresponde aos BDF atuais. Reemitir somente depois dos checks atuais.\n\nHashes SHA-256 dos arquivos selecionados da entrega. Permite detectar alteracao apos a verificacao. Nao possui hash de si proprio para evitar recursao. Bancos, work e saidas auxiliares modelsim nao selecionadas ficam fora. O pacote deve ser extraido e recompilado pelas fontes, com o SOF correspondente registrado em VALIDACAO.md.\n', encoding='utf-8', newline='\n')
    (ROOT / 'output_files/ULA_DE2_115.sof.md').write_text('# ULA_DE2_115.sof\n\nO arquivo presente e historico anterior a refatoracao visual enquanto docs/validacao_nativa_atual.json estiver PENDING. Nao foi recompilado a partir dos BDF atuais.\n\nImagem de configuracao volatil do FPGA EP4CE115F29C7, produzida pelo Assembly do Quartus 21.1 apos a compilacao dos 16 BDF finais. Nao foi programada na placa pelo agente. Seu SHA-256 e registrado em docs/verificacao_final.json e manifest.json. Recompilacao extraida pode gerar bytes diferentes por metadados, sem implicar fonte ou comportamento diferentes; a validacao compara fontes, dispositivo, pinos, recursos e sucesso das etapas. Confira JP6/JP7 antes de usar o Programmer.\n', encoding='utf-8', newline='\n')
    (ROOT / 'output_files/ULA_DE2_115.pin.md').write_text('# ULA_DE2_115.pin\n\nO arquivo presente e historico anterior a refatoracao enquanto docs/validacao_nativa_atual.json estiver PENDING; somente QSF/CSV foram conferidos no novo estado.\n\nRelatorio nativo de pinagem produzido pelo Fitter, somente leitura, nao e fonte de atribuicoes. Os 96 sinais declarados foram comparados ao CSV: pino, padrao de I/O e marca Y de atribuicao pelo usuario. Inclui tambem os pinos fisicos de alimentacao e nao usados do encapsulamento. Nao substitui a conferencia dos jumpers reais.\n', encoding='utf-8', newline='\n')


if __name__ == '__main__':
    main()
