from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DESCRIPTIONS = {
    'integrar.py': 'Regenera os grafos do core e do topo, QPF e QSF a partir do contrato congelado e do CSV de pinos. Os candidatos do mux e as conexões SW/LED/HEX são explícitos no código. Não gera HDL de implementação. Exemplo: python scripts/integrar.py na raiz da entrega. Validado por análise nativa, fitting e teste exaustivo do topo. Mudanças relevantes de arquitetura exigem atualização do contrato e dos documentos.',
    'validar_estrutura.py': 'Confere os 16 grafos: entidade e fonte presentes, nomes de instância únicos, aridade/direção/largura de portas, drivers únicos em cada rede consumida e ausência de ciclos combinacionais e hierárquicos. Expande bus ou bit para redes individuais; BUF é conexão lógica que o emissor materializa em dois NOT. Exemplo: python scripts/validar_estrutura.py. Passou nos 16 módulos e 342 instâncias; não substitui análise Quartus nem simulação do BDF exportado.',
    'preparar.py': 'Gera os BDF reais, analisa cada arquivo no Quartus, exporta Verilog, gera o BSF nativo e confere as portas do BSF/HDL contra o contrato. Retira fontes Verilog intermediárias da pasta de síntese; auxiliares ficam em simulation/generated e não entram no QSF. Mantém logs individuais. Exemplo: python scripts/preparar.py; --modules permite refazer blocos específicos. --root e --quartus ajustam caminhos. As 16 análises/conversões/símbolos passaram. Comentários não legais são removidos, preservando avisos de copyright/licença.',
    'gerar_pinagem.py': 'Extrai os pinos das páginas 36..39 do manual DE2-115 usando pypdf, cobrindo os 96 sinais declarados. Rejeita ausência ou duplicação de sinal/pino. JP6 e pinos fixos 3,3 V usam 3.3-V LVTTL; JP7 e pinos fixos 2,5 V usam 2.5 V. Exemplo: python scripts/gerar_pinagem.py caminho/DE2_115_User_manual.pdf. O CSV foi conferido com as imagens do enunciado e com as atribuições reais do Fitter. O manual externo é necessário só para regenerar o CSV, não para compilar o projeto.',
    'compilar.ps1': 'Executa quartus_sh --flow compile ULA_DE2_115 na raiz do projeto e falha se o processo retornar erro. Aceita -Quartus para o bin64 instalado. A compilação real inclui análise/síntese, fitting, assembly, TimeQuest e EDA writer. Não programa a placa. Exemplo: scripts/compilar.ps1. A revisão final passou com zero erros; os avisos são indexados e explicados em docs/VALIDACAO.md.',
    'render_evidencias.py': 'Lê diretamente a árvore BDF e renderiza símbolos, coordenadas, primitivas e conectores em PNG. Lê o VCD realmente executado para criar recortes de sinais observados; não calcula respostas esperadas. --circuits-only dispensa VCD. Usa Pillow e Arial local. Exemplo: python scripts/render_evidencias.py. As figuras são documentação programática do circuito e evidência de simulação, sem screenshot ou conferência da interface Quartus. O VCD completo preserva casos que não cabem no recorte.',
    'verificar_entrega.py': 'Confere o QSF com somente 16 BDF, interfaces BSF, ausência de processo sequencial no HDL exportado, arquivos/documentos de módulo, logs de testes aprovados, os 96 pinos/I/O e marca de atribuição no arquivo .pin do Fitter, zero registradores/memória/DSP/PLL e .sof presente. --manifest grava hashes SHA-256 de arquivos, excluindo bancos e auxiliares não portáteis. Exemplo: python scripts/verificar_entrega.py --manifest. Passou; o resumo é docs/verificacao_final.json. Não substitui teste em placa.',
    'limpar_gerados.py': 'Remove apenas comentários não legais de arquivos gerados, mantendo strings e avisos de Copyright/License Agreement. Antes de gravar exige igualdade dos tokens funcionais entre original e versão limpa. Exemplo: python scripts/limpar_gerados.py simulation/netlist/ula_de2_115.vo. A netlist foi compilada/simulada novamente depois da limpeza e o ZIP será recompilado com os símbolos limpos. Cabeçalhos legais preservados são a exceção documentada à ausência literal de comentários.',
    'simular_netlist.ps1': 'Gera .vo funcional pelo EDA Netlist Writer após a compilação dos BDF e simula no Icarus com cycloneive_atoms.v da instalação Quartus. Usa o testbench independente do topo em pasta isolada para preservar seu VCD modular. Aceita -IcarusRoot e -Quartus. Exemplo: scripts/simular_netlist.ps1. Passou nas 16384 verificações (8192 entradas únicas), após limpeza da netlist. O comando legado quartus_map --generate_functional_sim_netlist não é usado porque falhou com erro 281041 para Cyclone IV E. Não aplica SDF e não valida orçamento físico.',
    'empacotar.py': 'Cria ZIP com entrega/ como raiz, excluindo caches db/incremental_db, __pycache__, work e saídas automáticas modelsim não selecionadas. Inclui fontes, documentos, evidências e relatórios nativos relevantes. --extract exige diretório novo e rejeita travessia de caminho antes de extrair. Exemplo: python scripts/empacotar.py --extract tmp/recompilacao_zip. O teste de portabilidade requer compilar a cópia extraída e conferir pinos/estado, sem depender do banco original.',
    'documentar_apoio.py': 'Escreve documentos individuais dos scripts principais de apoio e dos dois grafos de integração, sem substituir os documentos específicos BDF/BSF. Exemplo: python scripts/documentar_apoio.py. Usa apenas pathlib; seus arquivos são auditados junto ao pacote. Não altera a implementação nem relata resultados sem os logs usados na validação.'
}


def main():
    for name, description in DESCRIPTIONS.items():
        (ROOT / 'scripts' / (name + '.md')).write_text('# ' + name + '\n\n' + description + '\n', encoding='utf-8')
    for name in ('ula_core', 'ula_de2_115'):
        (ROOT / 'config/grafos' / (name + '.json.md')).write_text(f'# {name}.json\n\nGrafo autoral de portas e redes da integracao aprovada. Instancias possuem entidade/primitiva, nome e conexoes por porta com intervalos explicitos de barramento. Emitido por integrar.py e lido por gerar_bdf.py; implementacao real em modulos/{name}.bdf, documentada em {name}.bdf.md. As interfaces sao do contrato congelado. Exemplo e trajeto completo dos sinais no documento BDF. Passou no verificador estrutural, analise/conversao Quartus e simulacao exaustiva do HDL exportado. Logs e limites em docs/VALIDACAO.md.\n', encoding='utf-8')
    (ROOT / 'docs/verificacao_final.json.md').write_text('# verificacao_final.json\n\nResumo real de verificar_entrega.py: numero de modulos, pinos/I/O conferidos com Fitter, zero recursos de estado/memoria/DSP e hash SHA-256 do SOF. E gerado somente apos os asserts passarem. A verificacao nao confirma jumpers, conferencia grafica ou teste fisico.\n', encoding='utf-8')
    (ROOT / 'manifest.json.md').write_text('# manifest.json\n\nHashes SHA-256 dos arquivos selecionados da entrega. Permite detectar alteracao apos a verificacao. Nao possui hash de si proprio para evitar recursao. Bancos, work e saidas auxiliares modelsim nao selecionadas ficam fora. O pacote deve ser extraido e recompilado pelas fontes, com o SOF correspondente registrado em VALIDACAO.md.\n', encoding='utf-8')
    (ROOT / 'output_files/ULA_DE2_115.sof.md').write_text('# ULA_DE2_115.sof\n\nImagem de configuracao volatil do FPGA EP4CE115F29C7, produzida pelo Assembly do Quartus 21.1 apos a compilacao dos 16 BDF finais. Nao foi programada na placa pelo agente. Seu SHA-256 e registrado em docs/verificacao_final.json e manifest.json. Recompilacao extraida pode gerar bytes diferentes por metadados, sem implicar fonte ou comportamento diferentes; a validacao compara fontes, dispositivo, pinos, recursos e sucesso das etapas. Confira JP6/JP7 antes de usar o Programmer.\n', encoding='utf-8')
    (ROOT / 'output_files/ULA_DE2_115.pin.md').write_text('# ULA_DE2_115.pin\n\nRelatorio nativo de pinagem produzido pelo Fitter, somente leitura, nao e fonte de atribuicoes. Os 96 sinais declarados foram comparados ao CSV: pino, padrao de I/O e marca Y de atribuicao pelo usuario. Inclui tambem os pinos fisicos de alimentacao e nao usados do encapsulamento. Nao substitui a conferencia dos jumpers reais.\n', encoding='utf-8')


if __name__ == '__main__':
    main()
